# -*- coding: utf-8 -*-
"""Streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CABxbW15ndw6Wfh_DVgYLW3WsipkrSdi
"""

# streamlit_app.py
import streamlit as st
import pandas as pd
import pickle

# Load model
with open("rf_model.pkl", "rb") as file:
    model = pickle.load(file)

st.title("🔐 Network Intrusion Detection")

# File uploader
uploaded_file = st.file_uploader("Upload CSV file with network data")

if uploaded_file is not None:
    try:
        data = pd.read_csv(uploaded_file)
        st.write("Preview of uploaded data:")
        st.write(data.head())

        # Prediction
        prediction = model.predict(data)
        st.write("Prediction results:")
        st.write(prediction)

    except Exception as e:
        st.error(f"Error: {e}")